### ISSUE TITLE
ISO 11179 EnumeratedValueDomain

### ISSUE THREAD

**Issue by hsolbrig** [opencimi/AML#7]
The DesignatableItem stereotype allows a set of language / sign / description tuples to be assigned to a NamedElement.  This represents a flattened version of the ItemDescription in the AML Meta Model.

Consider changing name to "Designatable_Item", explain more completely the relationship to 11179 concept, and provide hyperlink to 11179 specification.

**Comment by dksharma** [comment]
Stay consistent with camel-case.
