### ISSUE TITLE
DTV and Primitives Date, DateTime, Duration, Tim, AMLBoolean, AMLInteger, AMLReal, AMLString

### ISSUE THREAD

**Issue by neuronsong** [opencimi/AML#95]
Boolean type used for two-valued mathematical logic.

Does not appear to be any distinguishing semantic of these types vis-à-vis UML and/or XML data types.  These types hape applied stereotypes, but their use in defined mapping semantics could be expressed in a different way.
All of these Classifiers may be remove, with some adjustments to the AMLDataType Stereotype extensions and descriptions.

**Comment by hsolbrig** [comment]
AMLBoolean, AMLInteger, AMLString and AMLReal have been removed
