### ISSUE TITLE
DTV and Primitives MappedDataType

### ISSUE THREAD

**Issue by neuronsong** [opencimi/AML#98]
The MappedDataType stereotype extends a Class or DataType in the Reference Model.  It indicates that the base Class or DataType corresponds to the assumed AMLDataType referenced by amlType.
 
Reference Model implementors will need to define a mapping from the referenced amlType and the corresponding base Class or DataType that will transform the AML values into the corresponding target values.

Based on other recommendations, the AMLDataType Stereotype will no longer exist.  Constraints on the MappedDataType Stereotype should be adjusted to treat AMLDataType concept as implicit.  That includes validating that the implicit (formerly <<AMLDataType>>) Classifier referenced is in fact considered an internal AML DataType.

**Comment by hsolbrig** [comment]
AMLDataType Stereotype has been removed.  MappedDataType Stereotype needs to be adjusted to identify the target types explicitly
